# Generated by Django 5.0.6 on 2024-06-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('Id_dieta', models.IntegerField(primary_key=True, serialize=False)),
                ('Dieta', models.CharField(max_length=255)),
                ('Especificaciones', models.CharField(max_length=60)),
                ('Feche_entrega', models.TimeField()),
            ],
            options={
                'db_table': 'Dieta',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('N_identidad', models.AutoField(primary_key=True, serialize=False)),
                ('T_identidad', models.CharField(max_length=21)),
                ('Nombres', models.CharField(max_length=20)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Fecha_nacimiento', models.DateField()),
                ('Edad', models.IntegerField()),
                ('Grado', models.CharField(max_length=10)),
                ('Estado', models.CharField(max_length=10)),
                ('F_ingreso', models.TimeField()),
                ('FotoEstudiante', models.CharField(max_length=255)),
                ('Usuario_Id', models.IntegerField()),
            ],
            options={
                'db_table': 'Estudiante',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_producto', models.CharField(max_length=20)),
                ('Cantidad_p', models.IntegerField()),
                ('Fecha_compra', models.TimeField()),
                ('Fecha_caducidad', models.DateField()),
                ('Tipo_p', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('Id_reconocimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.TimeField()),
                ('Biometria', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Reconocimiento',
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('Id_sede', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_encargado', models.CharField(max_length=30)),
                ('N_encargado', models.IntegerField()),
            ],
            options={
                'db_table': 'Restaurante',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('Id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre_rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Pro_Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunchApp.dieta')),
                ('Id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunchApp.producto')),
            ],
            options={
                'db_table': 'Pro_Dieta',
            },
        ),
        migrations.CreateModel(
            name='Estu_Reco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_identidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunchApp.estudiante')),
                ('Id_reconocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunchApp.reconocimiento')),
            ],
            options={
                'db_table': 'Estu_Reco',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='Id_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunchApp.restaurante'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.CharField(max_length=20)),
                ('Clave', models.IntegerField()),
                ('FotoUsuario', models.CharField(max_length=255)),
                ('Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunchApp.rol')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
